# Generated by Django 3.1.2 on 2020-11-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='healthservices',
        ),
        migrations.DeleteModel(
            name='healthservices',
        ),
    ]
